#!/usr/bin/env bash
#install and configure HAproxy on your lb-01 server
sudo -i
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i "9i ENABLED=1" /etc/default/haproxy
cat >> /etc/haproxy/haproxy.cfg <<EOF

frontend haproxynode
    bind *:80
    mode http
    default_backend backendnodes

backend backendnodes
    balance roundrobin
    server 278963-web-02 34.234.193.138:80 check
    server 278963-web-01 54.90.54.163:80 check

EOF
sudo service haproxy restart
