#!/usr/bin/env bash
#install and configure HAproxy on your lb-01 server
sudo -i
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i "9i ENABLED=1" /etc/default/haproxy
cat >> /etc/haproxy/haproxy.cfg <<EOF

frontend haproxynode
    bind *:80
    mode http
    default_backend backendnodes

backend backendnodes
    balance roundrobin
    server 190348-web-02 54.242.159.226:80 check
    server 190348-web-01 3.84.222.31:80 check

EOF
sudo service haproxy restart
