#!/usr/bin/env bash
# Bash script that displays:
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal
i=0
while [ $1 -lt 1 ]
do
	echo "To infinity and beyond indefinitely"
	sleep 2
	trap "I am invincible!!!"
done
